# Decision Analytics & Optimization HW1

Team NCR

In [1]:
import numpy as np
import copy

Reference: https://www.geeksforgeeks.org/transportation-problem-set-4-vogels-approximation-method/

In [24]:
# cost matrix
cost = np.array([[ 92.63   , 104.03   , 145.945  , 112.42985, 107.79835, 112.1878 ],
       [160.2    ,  93.25   , 148.875  , 113.60875, 103.44625, 111.845  ],
       [186.696  , 122.31   , 112.31   , 135.97945, 127.76395, 133.3486 ],
       [127.344  ,  84.84   , 122.51   ,  73.34   ,  87.8403 ,  91.0404 ],
       [152.64   ,  95.15   , 144.725  , 107.61925,  89.15   , 106.999  ],
       [252.784  , 162.24   , 236.36   , 177.6178 , 168.9558 , 149.24   ]])
# capacity and demand array
capacity = np.array([22.0, 3.7, 4.5, 47.0, 18.5, 5.0])
demand = np.array([3.00, 2.60, 16.00, 20.00, 26.40, 11.90])

In [8]:
nrow = len(supply)
ncol = len(demand)

In [9]:
rowP = []
colP = []

In [11]:
for i in range(nrow):
    tmp = np.sort(cost[i])
    rowP.append(tmp[1] - tmp[0])
for j in range(ncol):
    tmp = cost[:,j][np.argsort(cost[:,j])]
    colP.append(tmp[1] - tmp[0])

In [17]:
rowP = np.array(rowP)
colP = np.array(colP)
rowP[np.isnan(rowP)] = 0
colP[np.isnan(colP)] = 0

In [18]:
rowP

array([11.4, 10.2, 10. , 11.5,  6. , 13. ])

In [19]:
colP

array([34.71,  8.41, 10.2 , 34.28,  1.31, 15.96])

In [21]:
def VAM(cost, supply, demand):
    _cost = copy.deepcopy(cost)
    _supply = copy.deepcopy(supply)
    _demand = copy.deepcopy(demand)
    # define the length of row & column
    nrow = len(_supply)
    ncol = len(_demand)
    # define an empty solution matrix
    solution = np.zeros(shape=(nrow, ncol))
    num_iter = 0
    # loop the process until supply or demand runs out
    while sum(_supply) > 0 and sum(_demand) > 0:
        # Step 1. Find the penalty (opportunity cost) for each row and column
        rowP = []
        colP = []
        # loop through each row & column
        for i in range(nrow):
            tmp = np.sort(_cost[i])
            rowP.append(tmp[1] - tmp[0])
        for j in range(ncol):
            tmp = _cost[:,j][np.argsort(_cost[:,j])]
            colP.append(tmp[1] - tmp[0])
        rowP = np.array(rowP)
        colP = np.array(colP)
        rowP[np.isnan(rowP)] = 0
        colP[np.isnan(colP)] = 0
        
        # Step 2. Decide the row/col with maximum penalty
        # cRow and cCol are the row/col locators for the cell to be modified
        cRow = 0
        cCol = 0
        if rowP.max() >= colP.max():
            cRow = np.argmax(rowP)
            cCol = np.argmin(_cost[cRow, :])
        else:
            cCol = np.argmax(colP)
            cRow = np.argmin(_cost[:, cCol])
        # Step 3. Allocate demand or supply to this cell
        # If demand is greater than supply, allocate supply to the cell, and exclude the row
        if _supply[cRow] >= _demand[cCol]:
            solution[cRow][cCol] = _demand[cCol]
            _supply[cRow] -= _demand[cCol]
            _demand[cCol] = 0
            _cost[:, cCol] = np.inf
        # If supply is greater than demand, allocate demand to the cell, and exclude the column
        else:
            solution[cRow][cCol] = _supply[cRow]
            _demand[cCol] -= _supply[cRow]
            _supply[cRow] = 0
            _cost[cRow, :] = np.inf

        num_iter+=1
        print('After %d iteration(s):' % num_iter)
        print('x%d=\n' % num_iter,solution)
        print('d%d=\n' % num_iter,_demand)
        print('s%d=\n' % num_iter,_supply)
        print()
    return solution

In [22]:
# Q2
# Supply is 100% capacity
supply = capacity
# Store & view the solution
sol = VAM(cost, supply, demand)
sol

After 1 iteration(s):
x1=
 [[3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
d1=
 [ 0.   2.6 16.  20.  26.4 11.9]
s1=
 [19.   3.7  4.5 47.  18.5  5. ]

After 2 iteration(s):
x2=
 [[ 3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 20.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
d2=
 [ 0.   2.6 16.   0.  26.4 11.9]
s2=
 [19.   3.7  4.5 27.  18.5  5. ]

After 3 iteration(s):
x3=
 [[ 3.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  20.   0.  11.9]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]]
d3=
 [ 0.   2.6 16.   0.  26.4  0. ]
s3=
 [19.   3.7  4.5 15.1 18.5  5. ]

After 4 iteration(s):
x4=
 [[ 3.   0.   0.   0.   0.   0. ]
 [ 0.   2.6  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  20.   0.  11.9]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   

/var/folders/yg/9f0w7r7n15z1jw7jxcgcdrvc0000gn/T/ipykernel_7975/1179453249.py:22: RuntimeWarning: invalid value encountered in double_scalars
  colP.append(tmp[1] - tmp[0])
/var/folders/yg/9f0w7r7n15z1jw7jxcgcdrvc0000gn/T/ipykernel_7975/1179453249.py:19: RuntimeWarning: invalid value encountered in double_scalars
  rowP.append(tmp[1] - tmp[0])


array([[ 3. ,  0. , 16. ,  0. ,  1.8,  0. ],
       [ 0. ,  2.6,  0. ,  0. ,  1.1,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , 20. ,  0. , 11.9],
       [ 0. ,  0. ,  0. ,  0. , 18.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  5. ,  0. ]])

In [5]:
# Calculate the total cost
sum(sum(sol * cost))/100

82.07626

In [150]:
# Q3
# Reduce the supply to 85% capacity and re-do the process
supply2 = capacity * 0.85
sol2 = VAM(cost, supply2, demand)
sol2

C:\Users\rochj\AppData\Local\Temp\ipykernel_45524\576714861.py:21: RuntimeWarning: invalid value encountered in double_scalars
  colP.append(tmp[1] - tmp[0])
C:\Users\rochj\AppData\Local\Temp\ipykernel_45524\576714861.py:18: RuntimeWarning: invalid value encountered in double_scalars
  rowP.append(tmp[1] - tmp[0])


array([[ 3.   ,  0.   ,  9.82 ,  0.   ,  5.88 ,  0.   ],
       [ 0.   ,  2.6  ,  0.   ,  0.   ,  0.545,  0.   ],
       [ 0.   ,  0.   ,  3.825,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  2.355, 20.   ,  0.   , 11.9  ],
       [ 0.   ,  0.   ,  0.   ,  0.   , 15.725,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  4.25 ,  0.   ]])

In [151]:
# New total cost with 85% capacity supply
sum(sum(sol2 * cost))/100

80.320498

In [152]:
# Q4
# Reduce the supply of chile to 0, and use 90% capacity
supply3 = capacity * 0.9
supply3[2] = 0
sol3 = VAM(cost, supply3, demand)
sol3

C:\Users\rochj\AppData\Local\Temp\ipykernel_45524\576714861.py:21: RuntimeWarning: invalid value encountered in double_scalars
  colP.append(tmp[1] - tmp[0])
C:\Users\rochj\AppData\Local\Temp\ipykernel_45524\576714861.py:18: RuntimeWarning: invalid value encountered in double_scalars
  rowP.append(tmp[1] - tmp[0])


array([[ 3.  ,  0.  , 12.28,  0.  ,  4.52,  0.  ],
       [ 0.  ,  2.6 ,  0.  ,  0.  ,  0.73,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  3.72, 20.  ,  0.  , 11.9 ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 16.65,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  4.5 ,  0.  ]])

In [153]:
# Total cost
sum(sum(sol3 * cost))/100

81.259612