# Vogel's approximation
## For balanced transportation problems, where sum(s) is identical to sum(d), and s and d are already known

In [1]:
import numpy as np
import pandas as pd

# define the initial variables
s=np.array([40,50,60])
d=np.array([30,20,45,55])

# build the matrix to be optimized
x=np.zeros((len(s), len(d)))

# create cost matrix
c=np.array([[9,4,6,6],
            [10,5,7,8],
            [4,7,3,5]])

# use a large m to present an infinite large
m=c.max()*1000

In [2]:
# start optimaization
while sum(s)>0:
    # exclude optimized rows and columns
    a=np.repeat(s!=0, len(d)).reshape(c.shape)
    b=np.repeat(d!=0, len(s)).reshape(c.shape,order="F")
    c[(a & b)!=True]=m

    # calculate opportunity cost arrays
    minc_s=np.repeat(c.min(axis=1), c.shape[1]).reshape(c.shape)
    opcost_s=c-minc_s
    opcost_s=np.sort(opcost_s, axis=1)
    opcost_s=opcost_s[:,1]

    minc_d=np.repeat(c.min(axis=0), c.shape[0]).reshape(c.shape,order="F")
    opcost_d=c-minc_d
    opcost_d=np.sort(opcost_d, axis=0)
    opcost_d=opcost_d[1,:]

    # find the index of s and d to be optimized
    maxcost=max(max(opcost_s),max(opcost_d))
    rows=opcost_s==maxcost
    cols=opcost_d==maxcost

    index1=np.repeat(rows, c.shape[1]).reshape(c.shape)
    index2=np.repeat(cols, c.shape[0]).reshape(c.shape,order="F")
    index=index1 | index2
    c_index=c*index
    ctmp=c_index+(c_index==0)*c_index.max() # replace 0 by the max number, therefore can use min() to find the minimun positive

    i=np.where(ctmp==ctmp.min())[0][0]
    j=np.where(ctmp==ctmp.min())[1][0]

    # upgrade x,s,d,flag
    x[i,j]=min(s[i],d[j])
    s[i]=s[i]-x[i,j]
    d[j]=d[j]-x[i,j]

    # output results after each iteration
    print("x=",x)
    print("d=",d)
    print("s=",s)
    print("\n")

x= [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [30.  0.  0.  0.]]
d= [ 0 20 45 55]
s= [40 50 30]


x= [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [30.  0. 30.  0.]]
d= [ 0 20 15 55]
s= [40 50  0]


x= [[ 0. 20.  0.  0.]
 [ 0.  0.  0.  0.]
 [30.  0. 30.  0.]]
d= [ 0  0 15 55]
s= [20 50  0]


x= [[ 0. 20.  0. 20.]
 [ 0.  0.  0.  0.]
 [30.  0. 30.  0.]]
d= [ 0  0 15 35]
s= [ 0 50  0]


x= [[ 0. 20.  0. 20.]
 [ 0.  0. 15.  0.]
 [30.  0. 30.  0.]]
d= [ 0  0  0 35]
s= [ 0 35  0]


x= [[ 0. 20.  0. 20.]
 [ 0.  0. 15. 35.]
 [30.  0. 30.  0.]]
d= [0 0 0 0]
s= [0 0 0]


